apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: 35.203.159.166
    http:
      paths:
      - backend:
          serviceName: cluster-ip-service
          servicePort: 4000
        path: /